package io.github.isht1008.opensmsbackup.gmail.backup

enum class GmailBackupStage {
    READING_LOCAL_SMS,
    BUILDING_LOCAL_CONVERSATIONS,
    CHECKING_LOCAL_CHECKPOINTS,
    RECOVERING_GMAIL_INDEX,
    COMPARING_CHANGED_CONVERSATIONS,
    UPLOADING_CHANGED_CONVERSATIONS,
    COMPLETING
}
